name: CI
on: [pull_request]
jobs:
  build-projects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build all projects
        run: |
          bash build-examples.sh

